--------------------------------------------------------
-- Archivo creado  - domingo-junio-14-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CATGORIA
--------------------------------------------------------

   CREATE SEQUENCE  "ADMINISTRADOR"."CATGORIA"  MINVALUE 0 MAXVALUE 99 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CODIGOCOMPUESTO
--------------------------------------------------------

   CREATE SEQUENCE  "ADMINISTRADOR"."CODIGOCOMPUESTO"  MINVALUE 0 MAXVALUE 99 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CODIGODETALLEVENTA
--------------------------------------------------------

   CREATE SEQUENCE  "ADMINISTRADOR"."CODIGODETALLEVENTA"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CODIGOMATERIAPRIMA
--------------------------------------------------------

   CREATE SEQUENCE  "ADMINISTRADOR"."CODIGOMATERIAPRIMA"  MINVALUE 0 MAXVALUE 99 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CODIGOPQRS
--------------------------------------------------------

   CREATE SEQUENCE  "ADMINISTRADOR"."CODIGOPQRS"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CODIGOPRODUCTO
--------------------------------------------------------

   CREATE SEQUENCE  "ADMINISTRADOR"."CODIGOPRODUCTO"  MINVALUE 0 MAXVALUE 999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence VENTACODIGO
--------------------------------------------------------

   CREATE SEQUENCE  "ADMINISTRADOR"."VENTACODIGO"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "ADMINISTRADOR"."CATEGORIA" 
   (	"CODIGOCATEGORIA" VARCHAR2(2 BYTE), 
	"NOMBRE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Table COMPUESTOPRODUCTO
--------------------------------------------------------

  CREATE TABLE "ADMINISTRADOR"."COMPUESTOPRODUCTO" 
   (	"CODIGOCOMPUESTO" VARCHAR2(2 BYTE), 
	"CANTIDADUNITARIA" NUMBER(1,0), 
	"CODIGOPRODUCTO" VARCHAR2(3 BYTE), 
	"CODIGOMATERIA" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Table DETALLEVENTA
--------------------------------------------------------

  CREATE TABLE "ADMINISTRADOR"."DETALLEVENTA" 
   (	"CODIGODETALLEVENTA" VARCHAR2(30 BYTE), 
	"CANTIDAD" NUMBER, 
	"TOTAL" NUMBER, 
	"CODIGOPRODUCTO" VARCHAR2(5 BYTE), 
	"CODIGOVENTA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Table CONTROL
--------------------------------------------------------

  CREATE TABLE "ADMINISTRADOR"."CONTROL" 
   (	"USUARIO" VARCHAR2(30 BYTE), 
	"FECHA" VARCHAR2(10 BYTE), 
	"OPERACION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Table MATERIAPRIMA
--------------------------------------------------------

  CREATE TABLE "ADMINISTRADOR"."MATERIAPRIMA" 
   (	"CODIGOMATERIA" VARCHAR2(2 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"CANTIDADENVASE" NUMBER(3,0), 
	"CANTIDAD" NUMBER(3,0), 
	"PRECIO" NUMBER(5,0), 
	"FECHAALMACENAMIENTO" VARCHAR2(10 BYTE), 
	"CODIGOCATEGORIA" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Table PQRS
--------------------------------------------------------

  CREATE TABLE "ADMINISTRADOR"."PQRS" 
   (	"CODIGOPQRS" VARCHAR2(10 BYTE), 
	"ASUNTO" VARCHAR2(100 BYTE), 
	"CONTENIDO" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "ADMINISTRADOR"."PRODUCTO" 
   (	"CODIGOPRODUCTO" VARCHAR2(3 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"PRECIOPRODUCTO" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "ADMINISTRADOR"."USUARIO" 
   (	"NOMBREUSUARIO" VARCHAR2(50 BYTE), 
	"CONTRASEÑA" VARCHAR2(50 BYTE), 
	"IDENTIFICACION" VARCHAR2(10 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Table VENDEDOR
--------------------------------------------------------

  CREATE TABLE "ADMINISTRADOR"."VENDEDOR" 
   (	"IDENTIFICACION" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Table VENTA
--------------------------------------------------------

  CREATE TABLE "ADMINISTRADOR"."VENTA" 
   (	"CODIGOVENTA" VARCHAR2(10 BYTE), 
	"VALORTOTAL" NUMBER, 
	"VALORDESCUENTO" NUMBER, 
	"SUBTOTAL" NUMBER, 
	"CODIGOVENDEDOR" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
REM INSERTING into ADMINISTRADOR.CATEGORIA
SET DEFINE OFF;
Insert into ADMINISTRADOR.CATEGORIA (CODIGOCATEGORIA,NOMBRE) values ('1','PANES');
Insert into ADMINISTRADOR.CATEGORIA (CODIGOCATEGORIA,NOMBRE) values ('2','CARNES');
Insert into ADMINISTRADOR.CATEGORIA (CODIGOCATEGORIA,NOMBRE) values ('3','PULPAS');
Insert into ADMINISTRADOR.CATEGORIA (CODIGOCATEGORIA,NOMBRE) values ('4','VERDURAS');
Insert into ADMINISTRADOR.CATEGORIA (CODIGOCATEGORIA,NOMBRE) values ('5','VEGETALES');
Insert into ADMINISTRADOR.CATEGORIA (CODIGOCATEGORIA,NOMBRE) values ('6','EMBUTIDOS');
Insert into ADMINISTRADOR.CATEGORIA (CODIGOCATEGORIA,NOMBRE) values ('7','QUESOS');
REM INSERTING into ADMINISTRADOR.COMPUESTOPRODUCTO
SET DEFINE OFF;
Insert into ADMINISTRADOR.COMPUESTOPRODUCTO (CODIGOCOMPUESTO,CANTIDADUNITARIA,CODIGOPRODUCTO,CODIGOMATERIA) values ('1','1','1','1');
REM INSERTING into ADMINISTRADOR.DETALLEVENTA
SET DEFINE OFF;
Insert into ADMINISTRADOR.DETALLEVENTA (CODIGODETALLEVENTA,CANTIDAD,TOTAL,CODIGOPRODUCTO,CODIGOVENTA) values ('25','100','160','1003','10');
Insert into ADMINISTRADOR.DETALLEVENTA (CODIGODETALLEVENTA,CANTIDAD,TOTAL,CODIGOPRODUCTO,CODIGOVENTA) values ('41','2','6000','1','21');
Insert into ADMINISTRADOR.DETALLEVENTA (CODIGODETALLEVENTA,CANTIDAD,TOTAL,CODIGOPRODUCTO,CODIGOVENTA) values ('4','3','3','13','1');
Insert into ADMINISTRADOR.DETALLEVENTA (CODIGODETALLEVENTA,CANTIDAD,TOTAL,CODIGOPRODUCTO,CODIGOVENTA) values ('5','3','3','13','1');
Insert into ADMINISTRADOR.DETALLEVENTA (CODIGODETALLEVENTA,CANTIDAD,TOTAL,CODIGOPRODUCTO,CODIGOVENTA) values ('21','4','4','13','30');
Insert into ADMINISTRADOR.DETALLEVENTA (CODIGODETALLEVENTA,CANTIDAD,TOTAL,CODIGOPRODUCTO,CODIGOVENTA) values ('22','4','92','32','30');
Insert into ADMINISTRADOR.DETALLEVENTA (CODIGODETALLEVENTA,CANTIDAD,TOTAL,CODIGOPRODUCTO,CODIGOVENTA) values ('23','4','92','32','30');
Insert into ADMINISTRADOR.DETALLEVENTA (CODIGODETALLEVENTA,CANTIDAD,TOTAL,CODIGOPRODUCTO,CODIGOVENTA) values ('24','3','69','32','9');
REM INSERTING into ADMINISTRADOR.CONTROL
SET DEFINE OFF;
Insert into ADMINISTRADOR.CONTROL (USUARIO,FECHA,OPERACION) values ('ADMINISTRADOR','14/06/20','INSERCION VENDEDOR');
REM INSERTING into ADMINISTRADOR.MATERIAPRIMA
SET DEFINE OFF;
Insert into ADMINISTRADOR.MATERIAPRIMA (CODIGOMATERIA,NOMBRE,CANTIDADENVASE,CANTIDAD,PRECIO,FECHAALMACENAMIENTO,CODIGOCATEGORIA) values ('1','Salchicha Ranchera','18','50','28000','12/06/2020','6');
REM INSERTING into ADMINISTRADOR.PQRS
SET DEFINE OFF;
REM INSERTING into ADMINISTRADOR.PRODUCTO
SET DEFINE OFF;
Insert into ADMINISTRADOR.PRODUCTO (CODIGOPRODUCTO,NOMBRE,PRECIOPRODUCTO) values ('1','Perro caliente','3000');
REM INSERTING into ADMINISTRADOR.USUARIO
SET DEFINE OFF;
Insert into ADMINISTRADOR.USUARIO (NOMBREUSUARIO,"CONTRASEÑA",IDENTIFICACION,EMAIL) values ('eduer.calvo','acuña','1003428295','calvoeduer@gmail.com');
Insert into ADMINISTRADOR.USUARIO (NOMBREUSUARIO,"CONTRASEÑA",IDENTIFICACION,EMAIL) values ('delisoft.admin','admin','00','00');
Insert into ADMINISTRADOR.USUARIO (NOMBREUSUARIO,"CONTRASEÑA",IDENTIFICACION,EMAIL) values ('mario.mendoza','admin','1066285875','menriquemendoza@unicesar.edu.co');
REM INSERTING into ADMINISTRADOR.VENDEDOR
SET DEFINE OFF;
Insert into ADMINISTRADOR.VENDEDOR (IDENTIFICACION,NOMBRE) values ('1002103759','Yesith Rojano');
Insert into ADMINISTRADOR.VENDEDOR (IDENTIFICACION,NOMBRE) values ('1066285875','mario mendoza');
Insert into ADMINISTRADOR.VENDEDOR (IDENTIFICACION,NOMBRE) values ('1003428296','eduer calvo');
Insert into ADMINISTRADOR.VENDEDOR (IDENTIFICACION,NOMBRE) values ('1002365482','Fernando Urquiza');
REM INSERTING into ADMINISTRADOR.VENTA
SET DEFINE OFF;
Insert into ADMINISTRADOR.VENTA (CODIGOVENTA,VALORTOTAL,VALORDESCUENTO,SUBTOTAL,CODIGOVENDEDOR) values ('10','159,68','30,72','160','1002103759');
Insert into ADMINISTRADOR.VENTA (CODIGOVENTA,VALORTOTAL,VALORDESCUENTO,SUBTOTAL,CODIGOVENDEDOR) values ('6','109,48','0','92','1003428296');
Insert into ADMINISTRADOR.VENTA (CODIGOVENTA,VALORTOTAL,VALORDESCUENTO,SUBTOTAL,CODIGOVENDEDOR) values ('7','3,57','0','3','1003428296');
Insert into ADMINISTRADOR.VENTA (CODIGOVENTA,VALORTOTAL,VALORDESCUENTO,SUBTOTAL,CODIGOVENDEDOR) values ('21','7140','0','6000','1003428296');
Insert into ADMINISTRADOR.VENTA (CODIGOVENTA,VALORTOTAL,VALORDESCUENTO,SUBTOTAL,CODIGOVENDEDOR) values ('1','7,14','0','6','1066285875');
Insert into ADMINISTRADOR.VENTA (CODIGOVENTA,VALORTOTAL,VALORDESCUENTO,SUBTOTAL,CODIGOVENDEDOR) values ('30','4,76','0','4','1066285875');
Insert into ADMINISTRADOR.VENTA (CODIGOVENTA,VALORTOTAL,VALORDESCUENTO,SUBTOTAL,CODIGOVENDEDOR) values ('8','10000','0','5000','1066285875');
Insert into ADMINISTRADOR.VENTA (CODIGOVENTA,VALORTOTAL,VALORDESCUENTO,SUBTOTAL,CODIGOVENDEDOR) values ('2','10000','0','5000','1066285875');
Insert into ADMINISTRADOR.VENTA (CODIGOVENTA,VALORTOTAL,VALORDESCUENTO,SUBTOTAL,CODIGOVENDEDOR) values ('3','10000','0','5000','1066285875');
Insert into ADMINISTRADOR.VENTA (CODIGOVENTA,VALORTOTAL,VALORDESCUENTO,SUBTOTAL,CODIGOVENDEDOR) values ('4','10000','0','5000','1066285875');
Insert into ADMINISTRADOR.VENTA (CODIGOVENTA,VALORTOTAL,VALORDESCUENTO,SUBTOTAL,CODIGOVENDEDOR) values ('5','10000','0','5000','1066285875');
Insert into ADMINISTRADOR.VENTA (CODIGOVENTA,VALORTOTAL,VALORDESCUENTO,SUBTOTAL,CODIGOVENDEDOR) values ('9','82,11','0','69','1003428296');
--------------------------------------------------------
--  DDL for Index SYS_C008966
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINISTRADOR"."SYS_C008966" ON "ADMINISTRADOR"."CATEGORIA" ("CODIGOCATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Index SYS_C008968
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINISTRADOR"."SYS_C008968" ON "ADMINISTRADOR"."COMPUESTOPRODUCTO" ("CODIGOCOMPUESTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Index SYS_C008740
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINISTRADOR"."SYS_C008740" ON "ADMINISTRADOR"."DETALLEVENTA" ("CODIGODETALLEVENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Index SYS_C008973
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINISTRADOR"."SYS_C008973" ON "ADMINISTRADOR"."MATERIAPRIMA" ("CODIGOMATERIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Index SYS_C008406
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINISTRADOR"."SYS_C008406" ON "ADMINISTRADOR"."PQRS" ("CODIGOPQRS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Index SYS_C008962
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINISTRADOR"."SYS_C008962" ON "ADMINISTRADOR"."PRODUCTO" ("CODIGOPRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Index SYS_C008394
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINISTRADOR"."SYS_C008394" ON "ADMINISTRADOR"."USUARIO" ("NOMBREUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Index SYS_C008749
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINISTRADOR"."SYS_C008749" ON "ADMINISTRADOR"."VENDEDOR" ("IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Index SYS_C008742
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINISTRADOR"."SYS_C008742" ON "ADMINISTRADOR"."VENTA" ("CODIGOVENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA" ;
--------------------------------------------------------
--  DDL for Trigger ELIMINARPRODUCTO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMINISTRADOR"."ELIMINARPRODUCTO" 
BEFORE DELETE ON materiaprima

BEGIN 
     INSERT INTO control (usuario, fecha, operacion) VALUES (user, sysdate, 'ELIMINAR PRODUCTO');
END eliminarproducto;    
/
ALTER TRIGGER "ADMINISTRADOR"."ELIMINARPRODUCTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ELIMINARMATERIAPRIMA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMINISTRADOR"."ELIMINARMATERIAPRIMA" 
BEFORE DELETE ON materiaprima

BEGIN 
     INSERT INTO control (usuario, fecha, operacion) VALUES (user, sysdate, 'ELIMINAR MATERIA');
END eliminarmateriaprima;   
/
ALTER TRIGGER "ADMINISTRADOR"."ELIMINARMATERIAPRIMA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ELIMINARVENDEDOR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMINISTRADOR"."ELIMINARVENDEDOR" 
BEFORE DELETE ON vendedor

BEGIN 
     INSERT INTO control (usuario, fecha, operacion) VALUES (user, sysdate, 'ELIMINAR VENDEDOR');
END eliminarvendedor;    
/
ALTER TRIGGER "ADMINISTRADOR"."ELIMINARVENDEDOR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INGRESARVENDEDOR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMINISTRADOR"."INGRESARVENDEDOR" 
BEFORE INSERT ON vendedor

BEGIN 
     INSERT INTO control (usuario, fecha, operacion) VALUES (user, sysdate, 'INSERCION VENDEDOR');
END ingresarvendedor;
/
ALTER TRIGGER "ADMINISTRADOR"."INGRESARVENDEDOR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSERTARMATERIAPRIMA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMINISTRADOR"."INSERTARMATERIAPRIMA" 
BEFORE INSERT ON materiaprima

BEGIN 
     INSERT INTO control (usuario, fecha, operacion) VALUES (user, sysdate, 'INSERTAR MATERIA');
END insertarmateriaprima;    
/
ALTER TRIGGER "ADMINISTRADOR"."INSERTARMATERIAPRIMA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSERTARVENTA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMINISTRADOR"."INSERTARVENTA" 
BEFORE INSERT ON venta

BEGIN 
     INSERT INTO control (usuario, fecha, operacion) VALUES (user, sysdate, 'INSERTAR VENTA');
END insertarventa;
/
ALTER TRIGGER "ADMINISTRADOR"."INSERTARVENTA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSERTARPRODUCTO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMINISTRADOR"."INSERTARPRODUCTO" 
BEFORE DELETE ON materiaprima

BEGIN 
     INSERT INTO control (usuario, fecha, operacion) VALUES (user, sysdate, 'INSERTAR PRODUCTO');
END insertarproducto;
/
ALTER TRIGGER "ADMINISTRADOR"."INSERTARPRODUCTO" ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "ADMINISTRADOR"."CATEGORIA" MODIFY ("CODIGOCATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR"."CATEGORIA" ADD PRIMARY KEY ("CODIGOCATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPUESTOPRODUCTO
--------------------------------------------------------

  ALTER TABLE "ADMINISTRADOR"."COMPUESTOPRODUCTO" MODIFY ("CODIGOCOMPUESTO" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR"."COMPUESTOPRODUCTO" ADD PRIMARY KEY ("CODIGOCOMPUESTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLEVENTA
--------------------------------------------------------

  ALTER TABLE "ADMINISTRADOR"."DETALLEVENTA" MODIFY ("CODIGODETALLEVENTA" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR"."DETALLEVENTA" ADD PRIMARY KEY ("CODIGODETALLEVENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIAPRIMA
--------------------------------------------------------

  ALTER TABLE "ADMINISTRADOR"."MATERIAPRIMA" MODIFY ("CODIGOMATERIA" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR"."MATERIAPRIMA" ADD PRIMARY KEY ("CODIGOMATERIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PQRS
--------------------------------------------------------

  ALTER TABLE "ADMINISTRADOR"."PQRS" MODIFY ("CODIGOPQRS" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR"."PQRS" ADD PRIMARY KEY ("CODIGOPQRS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DELISTUMERIENDA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ADMINISTRADOR"."PRODUCTO" MODIFY ("CODIGOPRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR"."PRODUCTO" ADD PRIMARY KEY ("CODIGOPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "ADMINISTRADOR"."USUARIO" MODIFY ("NOMBREUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR"."USUARIO" ADD PRIMARY KEY ("NOMBREUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENDEDOR
--------------------------------------------------------

  ALTER TABLE "ADMINISTRADOR"."VENDEDOR" MODIFY ("IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR"."VENDEDOR" ADD PRIMARY KEY ("IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "ADMINISTRADOR"."VENTA" MODIFY ("CODIGOVENTA" NOT NULL ENABLE);
  ALTER TABLE "ADMINISTRADOR"."VENTA" ADD PRIMARY KEY ("CODIGOVENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DELISTUMERIENDA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPUESTOPRODUCTO
--------------------------------------------------------

  ALTER TABLE "ADMINISTRADOR"."COMPUESTOPRODUCTO" ADD CONSTRAINT "FKCOMPUESTOPRODUCTO" FOREIGN KEY ("CODIGOPRODUCTO")
	  REFERENCES "ADMINISTRADOR"."PRODUCTO" ("CODIGOPRODUCTO") ENABLE;
  ALTER TABLE "ADMINISTRADOR"."COMPUESTOPRODUCTO" ADD CONSTRAINT "FKCOMPUESTOMATERIA" FOREIGN KEY ("CODIGOMATERIA")
	  REFERENCES "ADMINISTRADOR"."MATERIAPRIMA" ("CODIGOMATERIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLEVENTA
--------------------------------------------------------

  ALTER TABLE "ADMINISTRADOR"."DETALLEVENTA" ADD CONSTRAINT "FKDETALLEVENTA" FOREIGN KEY ("CODIGOVENTA")
	  REFERENCES "ADMINISTRADOR"."VENTA" ("CODIGOVENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATERIAPRIMA
--------------------------------------------------------

  ALTER TABLE "ADMINISTRADOR"."MATERIAPRIMA" ADD CONSTRAINT "FKCATEGORIA" FOREIGN KEY ("CODIGOCATEGORIA")
	  REFERENCES "ADMINISTRADOR"."CATEGORIA" ("CODIGOCATEGORIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "ADMINISTRADOR"."VENTA" ADD CONSTRAINT "FKVENTADETALLE" FOREIGN KEY ("CODIGOVENTA")
	  REFERENCES "ADMINISTRADOR"."VENTA" ("CODIGOVENTA") ENABLE;
  ALTER TABLE "ADMINISTRADOR"."VENTA" ADD CONSTRAINT "FKVENTAVENDEDOR" FOREIGN KEY ("CODIGOVENDEDOR")
	  REFERENCES "ADMINISTRADOR"."VENDEDOR" ("IDENTIFICACION") ENABLE;
